/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pluginapp_TestNative */

#ifndef _Included_com_example_pluginapp_TestNative
#define _Included_com_example_pluginapp_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pluginapp_TestNative
 * Method:    testNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pluginapp_TestNative_testNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
