/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_example_pluginapp_TestNative.h"
/*
 * Class:     com_example_pluginapp_TestNative
 * Method:    testNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pluginapp_TestNative_testNative
  (JNIEnv *env, jclass clazz)
{
	return (*env)->NewStringUTF(env,"hello from native");
}

